exports.barberos = [
	{
		id: 1,
		nombre: 'Juan',
		ap_paterno: 'García',
		ap_materno: 'Pérez',
		genero: 'masculino',
		telefono: '555-1234',
		foto: 'https://miurl.com/foto1.jpg',
		calle: 'Calle 1',
		colonia: 'Colonia 1',
		ciudad: 'Ciudad 1',
		numero: 123,
	},
	{
		id: 2,
		nombre: 'María',
		ap_paterno: 'López',
		ap_materno: 'Sánchez',
		genero: 'femenino',
		telefono: '555-5678',
		foto: 'https://miurl.com/foto2.jpg',
		calle: 'Calle 2',
		colonia: 'Colonia 2',
		ciudad: 'Ciudad 2',
		numero: 456,
	},
	{
		id: 3,
		nombre: 'Pedro',
		ap_paterno: 'Martínez',
		ap_materno: 'Ramírez',
		genero: 'masculino',
		telefono: '555-9012',
		foto: 'https://miurl.com/foto3.jpg',
		calle: 'Calle 3',
		colonia: 'Colonia 3',
		ciudad: 'Ciudad 3',
		numero: 789,
	},
	{
		id: 4,
		nombre: 'Laura',
		ap_paterno: 'González',
		ap_materno: 'Hernández',
		genero: 'femenino',
		telefono: '555-3456',
		foto: 'https://miurl.com/foto4.jpg',
		calle: 'Calle 4',
		colonia: 'Colonia 4',
		ciudad: 'Ciudad 4',
		numero: 1011,
	},
	{
		id: 5,
		nombre: 'Roberto',
		ap_paterno: 'Díaz',
		ap_materno: 'Pérez',
		genero: 'masculino',
		telefono: '555-7890',
		foto: 'https://miurl.com/foto5.jpg',
		calle: 'Calle 5',
		colonia: 'Colonia 5',
		ciudad: 'Ciudad 5',
		numero: 1213,
	},
	{
		id: 6,
		nombre: 'Ana',
		ap_paterno: 'Ramírez',
		ap_materno: 'Flores',
		genero: 'femenino',
		telefono: '555-2345',
		foto: 'https://miurl.com/foto6.jpg',
		calle: 'Calle 6',
		colonia: 'Colonia 6',
		ciudad: 'Ciudad 6',
		numero: 1415,
	},
	{
		id: 7,
		nombre: 'Jorge',
		ap_paterno: 'Gómez',
		ap_materno: 'Torres',
		genero: 'masculino',
		telefono: '555-6789',
		foto: 'https://miurl.com/foto7.jpg',
		calle: 'Calle 7',
		colonia: 'Colonia',
		ciudad: 'Ciudad 7',
		numero: 1617,
	},
	{
		id: 8,
		nombre: 'Lucía',
		ap_paterno: 'Fernández',
		ap_materno: 'Castillo',
		genero: 'femenino',
		telefono: '555-1234',
		foto: 'https://miurl.com/foto8.jpg',
		calle: 'Calle 8',
		colonia: 'Colonia 8',
		ciudad: 'Ciudad 8',
		numero: 1819,
	},
	{
		id: 9,
		nombre: 'Miguel',
		ap_paterno: 'González',
		ap_materno: 'Santos',
		genero: 'masculino',
		telefono: '555-5678',
		foto: 'https://miurl.com/foto9.jpg',
		calle: 'Calle 9',
		colonia: 'Colonia 9',
		ciudad: 'Ciudad 9',
		numero: 2021,
	},
	{
		id: 10,
		nombre: 'Marcela',
		ap_paterno: 'Vázquez',
		ap_materno: 'López',
		genero: 'femenino',
		telefono: '555-9012',
		foto: 'https://miurl.com/foto10.jpg',
		calle: 'Calle 10',
		colonia: 'Colonia 10',
		ciudad: 'Ciudad 10',
		numero: 2223,
	},
]
